### ISSUE TITLE
Error:  Cannot create GLX context.  Aborting.

### ISSUE THREAD

**Issue by qm-intel** [TomAmpiath/spectralUI#10]
@TomAmpiath Thanks for sharing you application

I tried with indian pine `mat` file and gave 400-2500 as input wavelength range.
I tried to view 3D hyperspectral but when I click to view 3D hypercube,  it closes the window and I am getting this error:
```
024-01-04 07:38:33.072 (  64.334s) [        D7FE2740]vtkXOpenGLRenderWindow.:635    ERR| vtkXOpenGLRenderWindow (0x29854d0): Cannot create GLX context.  Aborting.
Aborted (core dumped)
```
Do you have any idea how to solve this?

**Comment by TomAmpiath** [comment]
@qm-intel

Hi, can you please post your OS info and version of vtk package.

**Comment by TomAmpiath** [comment]
Closing the PR since no response... Will re-open if needed.
